### PR TITLE
Testimonial

### PR DESCRIPTION
**Pull request by Ankita297**
## What is the change?
Testimonial Section  added to website .
## Related issue?
close: #342 

## How was it tested?
 I have tested  it in my local system .

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [x] Did you lint your code before making the Pull Request?
- [x] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video:
Add a screenshot or demo video if appropriate.

https://user-images.githubusercontent.com/67833077/116255182-a37d6c80-a78f-11eb-9e07-4a13d0fda982.mp4

### CODE REVIEW

**Comment by Ankita297** [comment]
@Pranav016   Please review it now.
I have tested the code without that bootstrap scripts  but it is not working .

**Review by Pranav016 — APPROVED** [review]

**Comment by Pranav016** [comment]
/gssoc/

**Comment by Pranav016** [comment]
/level3/

**Comment by Ankita297** [comment]
@Pranav016 Thank You for helping me out throughout  the  issue .

**Comment by Pranav016** [comment]
> @Pranav016 Thank You for helping me out throughout the issue .

Thank you for your amazing work and contribution 😄

**Pull request merged**
