### PR TITLE
added admin middleware and edited user schema

### PR DESCRIPTION
**Pull request by Subham142**
## What is the change?
Remove this line and add a description

## Related issue?
close: #908 

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [x] Did you lint your code before making the Pull Request?
- [x] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

### CODE REVIEW

**Comment by Subham142** [comment]
@Pranav016  please review and merge it
so that I can work on the routes and controllers

**Review by Pranav016 — CHANGES_REQUESTED** [review]
There are changes to the package-lock which are not required.
check README for instructions for package-lock version 2

**Comment by Subham142** [comment]
@Pranav016  I updated the npm  please review it

**Comment by Pranav016** [comment]
> @Pranav016 I updated the npm please review it

You need to revert the changes in package-lock, there are still some changes in it..

Also don't tag me if it hasn't been more than 36hrs since the PR hasn't been reviewed. I try to review it every day at a particular time.

**Comment by Subham142** [comment]
I'll close this pr and send you a new one

**Pull request closed without merging**
