### PR TITLE
Update Overlapping buttons in carousel

### PR DESCRIPTION
**Pull request by SamikshaSankar**
## What is the change?
Overlapping button in carousal in responsive

## Related issue?
close: #983 

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [] Did you lint your code before making the Pull Request?
- [] Have you made corresponding changes to the documentation?
- [] Your submission doesn't break any existing feature.
- [] Have you tested the code before submission?

IMG_20210621_141754

### CODE REVIEW

**Comment by Ayush0730** [comment]
Always add a demo after doing changes, to show it is working fine

**Comment by SamikshaSankar** [comment]
> Always add a demo after doing changes, to show it is working fine



> Always add a demo after doing changes, to show it is working fine

@Ayush0730 okay...is it working? Or I have to made other changes in that

**Comment by Ayush0730** [comment]
LGTM

**Review by Pranav016 — APPROVED** [review]

**Comment by Pranav016** [comment]
Next time write commit messages like- `Fix Overlapping buttons in carousel`

**Pull request merged**
