### PR TITLE
Dockerized Wordnook 

### PR DESCRIPTION
**Pull request by theBeginner86**
## What is the change?
I've dockerized this project. 🐬🐬

- Created an account of alphavio on the docker hub.
- I created an image for the project and pushed it to the docker hub.
- Created a docker-compose.yml file so that the setup instruction could be automated and run with just one command: `docker-compose up --build`
- Also, update the READE.md file and added setup instructions for installation of the project.

@Pranav016 I know that you asked in the PR #705 to make the docker-compose file to pull the image from Docker Hub but the thing is that if a contributor pulls our image from docker hub then when they want to make any changes then those changes will not be replicated in our image at Docker Hub. So, they won't be able to develop and debug because every time they would run `docker-compose up` then only the image which we have already put on docker hub would be pulled which would not contain the changes.
So, I thought that let the contributor itself make a new image every time they make changes so that at least they can see the changes on their local system. Moreover, once they make a PR and we merge it, then we ourselves could push the new image to Docker Hub. Though we can also set up CI/CD pipeline using Jenkins but, I'm not sure about it yet as I'm still learning. Though we can raise an issue for it later or we could add it ourselves later on.
Also, I saw other projects as well which use Docker and they also make the contributor build the image for testing. They don't make the contributor pull the image from the docker hub. Even the [docker docs](https://github.com/docker/docker.github.io) repo was doing like this only.

I've shared alphavio's docker credentials on discord DM.
Let me know if you need any explanations about any part of this PR. Do share your views as well. 😁

## Related issue?
close: #365

## How was it tested?
Tested locally

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [x] Did you lint your code before making the Pull Request?
- [x] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video:

https://user-images.githubusercontent.com/73700530/126799890-5efe7c47-c227-48eb-bc64-8c26ffa78d1f.mp4

### CODE REVIEW

**Comment by theBeginner86** [comment]
Actually, I forgot to add the env variables in the docker-compose.yml file. So, I just added them.

**Comment by Pranav016** [comment]
> ## What is the change?
> I've dockerized this project. 🐬🐬
> 
> * Created an account of alphavio on the docker hub.
> * I created an image for the project and pushed it to the docker hub.
> * Created a docker-compose.yml file so that the setup instruction could be automated and run with just one command: `docker-compose up --build`
> * Also, update the READE.md file and added setup instructions for installation of the project.
> 
> @Pranav016 I know that you asked in the PR #705 to make the docker-compose file to pull the image from Docker Hub but the thing is that if a contributor pulls our image from docker hub then when they want to make any changes then those changes will not be replicated in our image at Docker Hub. So, they won't be able to develop and debug because every time they would run `docker-compose up` then only the image which we have already put on docker hub would be pulled which would not contain the changes.
> So, I thought that let the contributor itself make a new image every time they make changes so that at least they can see the changes on their local system. Moreover, once they make a PR and we merge it, then we ourselves could push the new image to Docker Hub. Though we can also set up CI/CD pipeline using Jenkins but, I'm not sure about it yet as I'm still learning. Though we can raise an issue for it later or we could add it ourselves later on.
> Also, I saw other projects as well which use Docker and they also make the contributor build the image for testing. They don't make the contributor pull the image from the docker hub. Even the [docker docs](https://github.com/docker/docker.github.io) repo was doing like this only.
> 
> I've shared alphavio's docker credentials on discord DM.
> Let me know if you need any explanations about any part of this PR. Do share your views as well. 😁


Got your point, you are right 👍

**Comment by Pranav016** [comment]
Should we add docker files to `slugignore` since they are not required to be pushed to heroku right ?

**Review by Pranav016 — APPROVED** [review]

**Comment by theBeginner86** [comment]
> Should we add docker files to `slugignore` since they are not required to be pushed to heroku right ?

Yes, I think we should do it. 👍

**Comment by theBeginner86** [comment]
- I've added docker files to .slugignore
- Also, added the .env file in .dockerignore so that if contributor by chance setups .env file for using standard installations and then want to go for docker installation as well, then docker build won't get confused from environment variables coming from .env file as well as docker-compose.yml file.

**Comment by Pranav016** [comment]
> * I've added docker files to .slugignore
> * Also, added the .env file in .dockerignore so that if contributor by chance setups .env file for using standard installations and then want to go for docker installation as well, then docker build won't get confused from environment variables coming from .env file as well as docker-compose.yml file.

Gotcha 👍

**Pull request merged**
