### PR TITLE
issue #762 fixed - edited hover effect on footer links

### PR DESCRIPTION
**Pull request by SachindraFernando**
## What is the change?
Added hover effect on footer links.

## Related issue?
close: #762

## How was it tested?
Remove this line and tell us how the code was tested.

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [] Did you lint your code before making the Pull Request?
- [] Have you made corresponding changes to the documentation?
- [] Your submission doesn't break any existing feature.
- [] Have you tested the code before submission?

## Screenshots or Video:
Add a screenshot or demo video if appropriate.

### CODE REVIEW

**Comment by Pranav016** [comment]
Can you add a demo here

**Comment by Pranav016** [comment]
/gssoc/

**Comment by Pranav016** [comment]
/level2/

**Comment by SachindraFernando** [comment]
> Can you add a demo here

Sure sir.

https://user-images.githubusercontent.com/37910436/116460390-a4dc9100-a884-11eb-8d07-243e20c96995.mp4

**Review by Pranav016 — APPROVED** [review]

**Comment by Pranav016** [comment]
/gssoc/

**Comment by Pranav016** [comment]
/level2/

**Comment by Pranav016** [comment]
Good work

**Comment by SachindraFernando** [comment]
> Good work

Thank you sir

**Pull request merged**
