### PR TITLE
added all contributors automerge

### PR DESCRIPTION
**Pull request by subhangi2731**
## What is the change?
Added automerge PRs from all contributors bot

## Related issue?
close: #323

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [x] Did you lint your code before making the Pull Request?
- [x] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

### CODE REVIEW

**Comment by subhangi2731** [comment]
@Pranav016 please merge my pr

**Comment by Pranav016** [comment]
Did you test this action ? I noticed a couple things that might cause issue.

**Comment by subhangi2731** [comment]
@Pranav016 no I didn't test point this issue since I have no all contributors installed

**Comment by subhangi2731** [comment]
please merge my pr @Pranav016

**Comment by Pranav016** [comment]
> please merge my pr @Pranav016

I cannot merge unless I know it works..

**Comment by Pranav016** [comment]
> @Pranav016 no I didn't test point this issue since I have no all contributors installed

No worries, you can use this repo for that - https://github.com/Pranav016/test-action
Just make a PR with your action and I'll merge it. Then you can test it.

**Comment by subhangi2731** [comment]
@Pranav016 I made a pr in that repo please check and merge now

**Comment by Pranav016** [comment]
Reference https://github.com/Pranav016/test-action/pull/5

**Comment by subhangi2731** [comment]
@pranav u have merged my pr there in the different repo of urs which u had told to send the pr there to test but I have not got points for this please tell the gssoc team to give me points as u have merged my pr which i had given in ur repo

**Comment by Pranav016** [comment]
> @pranav u have merged my pr there in the different repo of urs which u had told to send the pr there to test but I have not got points for this please tell the gssoc team to give me points as u have merged my pr which i had given in ur repo

@subhangi2731 Is the code in this PR working?

**Pull request closed without merging**
