### PR TITLE
Changed the background of testimonial

### PR DESCRIPTION
**Pull request by RuchiGitHu**
## What is the change?
As each wall and piece of website has background color, I want to put background color in testimonial of home page so that it look like landing page of website.

## Related issue?
close: #859 

## How was it tested?
Tested locally.

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [] Did you lint your code before making the Pull Request?
- [] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video:
I have added the background color in testimonial section of home page.

image
image
You can also change the color of background according to future development in website.

### CODE REVIEW

**Comment by RuchiGitHu** [comment]
Please review @Pranav016

**Comment by Pranav016** [comment]
> Please review @Pranav016

Please do not tag unless it's been more than 36 hrs since the PR has been made

**Comment by Pranav016** [comment]
I don't think this matches the aesthetic of the website

**Comment by RuchiGitHu** [comment]
> I don't think this matches the aesthetic of the website

If you want I can change the background from the existing front page background which is in blue colour, I thought this so that the testimonial looks good and effective like other section.

**Comment by Pranav016** [comment]
I think it was fine being white

**Comment by Pranav016** [comment]
> > I think it was fine being white
> 
> As you can see the background color and testimonial thoughts box (comments) color is matching too much.
> image
> 
> Below is the example of what I am trying to say, that comments of each testimonial should looks different and more visible to anyone.
> image
> The approach can be done by two ways, first : we can change the background of whole testimonial section so that the comments will highlight automatically , second : just to change background color of each comment in testimonial.
> Looking forward for your reply.

Give the testimonial card a very light and subttle background

**Comment by RuchiGitHu** [comment]
Please review @Pranav016

**Comment by Pranav016** [comment]
Add a screenshot here

**Comment by RuchiGitHu** [comment]
> Add a screenshot here

image
image
image

**Comment by Pranav016** [comment]
> > Add a screenshot here
> 
> image
> image
> image

the text is less visible in this color, either make the background lighter or the text darker

**Comment by RuchiGitHu** [comment]
image
Please review @Pranav016 
image

**Review by Pranav016 — APPROVED** [review]

**Pull request merged**
