### PR TITLE
Maintainers card added

### PR DESCRIPTION
**Pull request by theBeginner86**
## What is the change?
Added the maintainer's card in the README.md

## Related issue?
close: #issue_number

## How was it tested?
Tested locally.

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [x] Did you lint your code before making the Pull Request?
- [] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video:
Screenshot 2021-06-11 at 8 19 26 PM

### CODE REVIEW

**Comment by Pranav016** [comment]
Don't remove the previous ones

**Comment by theBeginner86** [comment]
Made the changes

Screenshot 2021-06-12 at 8 07 55 AM

**Comment by Pranav016** [comment]
Don't write commit messages like this `aligned my emoji with the rest`. One way of writing good commit messages is just think of them in the perspective of a person who has just cloned the project and is looking at commit logs. He should be able to tell the change in each commit. Even though the message is descriptive but it still lacks some information like whose emoji or where the emoji was aligned.

Just some feedback to help 🙂 I hope you take it constructively

**Comment by Pranav016** [comment]
I'll also share some guides on writing good commit messages.

**Comment by theBeginner86** [comment]
> Don't write commit messages like this `aligned my emoji with the rest`. One way of writing good commit messages is just think of them in the perspective of a person who has just cloned the project and is looking at commit logs. He should be able to tell the change in each commit. Even though the message is descriptive but it still lacks some information like whose emoji or where the emoji was aligned.
> 
> Just some feedback to help 🙂 I hope you take it constructively

okay, sure. I totally understand your point. Will try to take it into consideration for future commits.
May I amend it, if you want?

**Comment by Pranav016** [comment]
> > Don't write commit messages like this `aligned my emoji with the rest`. One way of writing good commit messages is just think of them in the perspective of a person who has just cloned the project and is looking at commit logs. He should be able to tell the change in each commit. Even though the message is descriptive but it still lacks some information like whose emoji or where the emoji was aligned.
> > Just some feedback to help 🙂 I hope you take it constructively
> 
> okay, sure. I totally understand your point. Will try to take it into consideration for future commits.
> May I amend it, if you want?

Yes you can

**Pull request merged**
