### PR TITLE
fix: Handled footer in testinomials wall

### PR DESCRIPTION
**Pull request by keshavgbpecdelhi**
## What is the change?
The footer for testimonial-wall was not covering the full screen in desktop as well as mobile mode. Fixed it.

## Related issue?
close: #948

## How was it tested?
The code was tested in local environment at port 3000

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [X] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [X] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [X] Did you lint your code before making the Pull Request?
- [X] Your submission doesn't break any existing feature.
- [X] Have you tested the code before submission?

## Screenshots or Video:
Add a screenshot or demo video if appropriate- 

# Before Screenshot :

image

# After Screenshot :

image

### CODE REVIEW

**Comment by AnanyaNegi** [comment]
Hey @keshavgbpecdelhi can you post a before and after video of the issue? Since when I'm viewing it in my localhost, the footer is responsive.

**Review by AnanyaNegi — CHANGES_REQUESTED** [review]
What's the change in code?

**Comment by keshavgbpecdelhi** [comment]
> What's the change in code?

@AnanyaNegi click on the pull request, and you can see the changes. Remember :
Green  color for editing new code.
Red color for removing previous.
Github allows everyone to review and watch the code edits.

And 


> Hey @keshavgbpecdelhi can you post a before and after video of the issue? Since when I'm viewing it in my localhost, the footer is responsive.

Yes, let me show it by video if you ask for that, but I don't think it's that hard to find, if you read the issue again and compare the screenshot with the live site testimonials-wall you can see the changes.

Thankyou

**Comment by keshavgbpecdelhi** [comment]
@AnanyaNegi ok I edited the before and after screenshot both in the PR description. I think I made it very much clear now. Still doubt you can ask. Happy to solve :)

**Review by Pranav016 — CHANGES_REQUESTED** [review]
PR is almost ready to merge. A few changes.
- Commit message is absolutely not acceptable, please update it. You can use the --amend flag while committing to update the commit msg and then force push.
- There are changes to the package-lock file which are not required. Please read the README file to understand it better.
- There is a binary file added in views folder by the name of `.testimonial-wall.ejs.swp ` which I don't get if its of any use. Comment if disagree

**Comment by keshavgbpecdelhi** [comment]
> PR is almost ready to merge. A few changes.
> 
> * Commit message is absolutely not acceptable, please update it. You can use the --amend flag while committing to update the commit msg and then force push.
> * There are changes to the package-lock file which are not required, it related to lockfile version. Please read the README file to understand it better.
> * There is a binary file added in views folder by the name of `.testimonial-wall.ejs.swp ` which I don't get if its of any use. Comment if disagree

@Pranav016 Thanks, yes I agree with you.  Did the required changes. Let me know if something else needed to be done.

**Review by Pranav016 — APPROVED** [review]

**Pull request merged**
