### PR TITLE
prelaoder updated

### PR DESCRIPTION
**Pull request by Ankita297**
## What is the change?
preloader updated
## Related issue?
close: #971

## How was it tested?
I have tested it in my local system
## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [x] Did you lint your code before making the Pull Request?
- [x] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video:
Add a screenshot or demo video if appropriate.
localhost - Google Chrome 31-05-2021 14_53_46

https://user-images.githubusercontent.com/67833077/120174605-e44f2200-c222-11eb-81dd-fb165bf8eeb7.mp4

### CODE REVIEW

**Comment by Pranav016** [comment]
Remove the preloader and its code added in #919 . Also add a screenshot of how the preloader looks in dark mode

**Comment by Ankita297** [comment]
Sir i have use navbar color ,it is looking same in both the mode .

**Comment by Ankita297** [comment]
is it okay now ?

**Review by Pranav016 — APPROVED** [review]

**Comment by Pranav016** [comment]
@Ankita297 would you like to be a maintainer for ALPHAVIO projects after GSSoC ?
We need mentors since we are participating in another open-source event. Projects to be looked after are WordNook and Mirage-UI.
Join the ALPHAVIO discord if you wish to work with the org. (Link in README)

**Comment by Pranav016** [comment]
> @Ankita297 would you like to be a maintainer for ALPHAVIO projects after GSSoC ?
> We need mentors since we are participating in another open-source event. Projects to be looked after are WordNook and Mirage-UI.
> Join the ALPHAVIO discord if you wish to work with the org. (Link in README)

@Ankita297

**Comment by Ankita297** [comment]
@Pranav016  I would like to . Thank you so much for the opportunity   and giving me the chance .

**Pull request merged**
